# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: self-hosted 

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore Bootcamp_API/Bootcamp_API.csproj
    - name: Build
      run: dotnet build Bootcamp_API/Bootcamp_API.csproj --no-restore --configuration Release
    - name: Test
      run: dotnet test Bootcamp_API/Bootcamp_API.csproj --no-build --verbosity normal